/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface Store_moneyInterface extends Interface {
  getFunction(
    nameOrSignature: "amount" | "customer" | "deposit_money" | "deposit_view"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DepositRecorded"): EventFragment;

  encodeFunctionData(functionFragment: "amount", values?: undefined): string;
  encodeFunctionData(functionFragment: "customer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "deposit_money",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit_view",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "amount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "customer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deposit_money",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deposit_view",
    data: BytesLike
  ): Result;
}

export namespace DepositRecordedEvent {
  export type InputTuple = [
    customer: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    customer: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    customer: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Store_money extends BaseContract {
  connect(runner?: ContractRunner | null): Store_money;
  waitForDeployment(): Promise<this>;

  interface: Store_moneyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  amount: TypedContractMethod<[], [bigint], "view">;

  customer: TypedContractMethod<[], [string], "view">;

  deposit_money: TypedContractMethod<
    [customer_input: AddressLike, amount_input: BigNumberish],
    [void],
    "nonpayable"
  >;

  deposit_view: TypedContractMethod<[], [[string, bigint]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "amount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "customer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deposit_money"
  ): TypedContractMethod<
    [customer_input: AddressLike, amount_input: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit_view"
  ): TypedContractMethod<[], [[string, bigint]], "view">;

  getEvent(
    key: "DepositRecorded"
  ): TypedContractEvent<
    DepositRecordedEvent.InputTuple,
    DepositRecordedEvent.OutputTuple,
    DepositRecordedEvent.OutputObject
  >;

  filters: {
    "DepositRecorded(address,uint256,uint256)": TypedContractEvent<
      DepositRecordedEvent.InputTuple,
      DepositRecordedEvent.OutputTuple,
      DepositRecordedEvent.OutputObject
    >;
    DepositRecorded: TypedContractEvent<
      DepositRecordedEvent.InputTuple,
      DepositRecordedEvent.OutputTuple,
      DepositRecordedEvent.OutputObject
    >;
  };
}
