/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  Store_money,
  Store_moneyInterface,
} from "../../deposit.sol/Store_money";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "customer",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "DepositRecorded",
    type: "event",
  },
  {
    inputs: [],
    name: "amount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "customer",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "customer_input",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount_input",
        type: "uint256",
      },
    ],
    name: "deposit_money",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "deposit_view",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610371806100206000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80632804b2c014610051578063aa8c217c1461006f578063ada9f83a1461008d578063c38021e3146100a9575b600080fd5b6100596100c8565b60405161006691906101fd565b60405180910390f35b6100776100ec565b6040516100849190610231565b60405180910390f35b6100a760048036038101906100a291906102a9565b6100f2565b005b6100b161018d565b6040516100bf9291906102e9565b60405180910390f35b60008054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b60015481565b816000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550806001819055508173ffffffffffffffffffffffffffffffffffffffff167f63746a529035c061c0f4d3d89777a673fe489a291caf751b3a0c40b7c89448a48242604051610181929190610312565b60405180910390a25050565b60008060008054906101000a900473ffffffffffffffffffffffffffffffffffffffff16600154915091509091565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006101e7826101bc565b9050919050565b6101f7816101dc565b82525050565b600060208201905061021260008301846101ee565b92915050565b6000819050919050565b61022b81610218565b82525050565b60006020820190506102466000830184610222565b92915050565b600080fd5b61025a816101dc565b811461026557600080fd5b50565b60008135905061027781610251565b92915050565b61028681610218565b811461029157600080fd5b50565b6000813590506102a38161027d565b92915050565b600080604083850312156102c0576102bf61024c565b5b60006102ce85828601610268565b92505060206102df85828601610294565b9150509250929050565b60006040820190506102fe60008301856101ee565b61030b6020830184610222565b9392505050565b60006040820190506103276000830185610222565b6103346020830184610222565b939250505056fea2646970667358221220a6dadb6f92ac03d882f68e637d685ca7f0862e5aa593b5a9ad3e41970e7f6d2464736f6c63430008140033";

type Store_moneyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: Store_moneyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Store_money__factory extends ContractFactory {
  constructor(...args: Store_moneyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Store_money & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Store_money__factory {
    return super.connect(runner) as Store_money__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Store_moneyInterface {
    return new Interface(_abi) as Store_moneyInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Store_money {
    return new Contract(address, _abi, runner) as unknown as Store_money;
  }
}
