/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as depositSol from "./deposit.sol";
export type { depositSol };
export type { Paynow } from "./Paynow";
export * as factories from "./factories";
export type { Store_money } from "./deposit.sol/Store_money";
export { Store_money__factory } from "./factories/deposit.sol/Store_money__factory";
export { Paynow__factory } from "./factories/Paynow__factory";
