/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PaynowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "amount"
      | "check_transaction"
      | "owner"
      | "payee"
      | "payer"
      | "weixin"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "TransactionRecorded"): EventFragment;

  encodeFunctionData(functionFragment: "amount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "check_transaction",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "payee", values?: undefined): string;
  encodeFunctionData(functionFragment: "payer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "weixin",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "amount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "check_transaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "weixin", data: BytesLike): Result;
}

export namespace TransactionRecordedEvent {
  export type InputTuple = [
    payer: AddressLike,
    payee: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    payer: string,
    payee: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    payer: string;
    payee: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Paynow extends BaseContract {
  connect(runner?: ContractRunner | null): Paynow;
  waitForDeployment(): Promise<this>;

  interface: PaynowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  amount: TypedContractMethod<[], [bigint], "view">;

  check_transaction: TypedContractMethod<
    [],
    [[string, string, bigint]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  payee: TypedContractMethod<[], [string], "view">;

  payer: TypedContractMethod<[], [string], "view">;

  weixin: TypedContractMethod<
    [
      payer_add: AddressLike,
      payee_add: AddressLike,
      amount_transfer: BigNumberish
    ],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "amount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "check_transaction"
  ): TypedContractMethod<[], [[string, string, bigint]], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payee"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "weixin"
  ): TypedContractMethod<
    [
      payer_add: AddressLike,
      payee_add: AddressLike,
      amount_transfer: BigNumberish
    ],
    [void],
    "payable"
  >;

  getEvent(
    key: "TransactionRecorded"
  ): TypedContractEvent<
    TransactionRecordedEvent.InputTuple,
    TransactionRecordedEvent.OutputTuple,
    TransactionRecordedEvent.OutputObject
  >;

  filters: {
    "TransactionRecorded(address,address,uint256,uint256)": TypedContractEvent<
      TransactionRecordedEvent.InputTuple,
      TransactionRecordedEvent.OutputTuple,
      TransactionRecordedEvent.OutputObject
    >;
    TransactionRecorded: TypedContractEvent<
      TransactionRecordedEvent.InputTuple,
      TransactionRecordedEvent.OutputTuple,
      TransactionRecordedEvent.OutputObject
    >;
  };
}
